development:
  adapter: mysql
  database: podcast_development
  username: root
  host: 127.0.0.1
  
test:
  adapter: mysql
  database: podcast_test
  username: root
  host: 127.0.0.1

production:
  adapter: mysql
  database: podcast
  username: podcast
  password: podcast
  socket: /var/run/mysqld/mysqld.sock
